### ISSUE TITLE
ASGC+Typhoon plot generation is failing. 

### ISSUE THREAD

**Issue by jayatsandia** [sunspec/svp_UL1741SA#3]
I don't know if it's a 3-phase problem or not. 

Here's an example. 

2018-04-16 15:57:02.931  E  Test script exception: Traceback (most recent call last):
  File "D:\SVP\SVP Directories 4-13-18\svp_UL1741SA\UL1741 SA\Scripts\SA12_power_factor.py", line 337, in run
    result = test_run()
  File "D:\SVP\SVP Directories 4-13-18\svp_UL1741SA\UL1741 SA\Scripts\SA12_power_factor.py", line 319, in test_run
    rslt.result_workbook(file, ts.results_dir(), ts.result_dir())
  File "D:\SVP\SVP Directories 4-13-18\svp_UL1741SA\UL1741 SA\Lib\svpelab\result.py", line 71, in result_workbook
    index_row=0)
  File "D:\SVP\SVP Directories 4-13-18\svp_UL1741SA\UL1741 SA\Lib\svpelab\result.py", line 246, in to_xlsx
    result_wb.close()
  File "D:\SVP\SVP Directories 4-13-18\svp_UL1741SA\UL1741 SA\Lib\svpelab\result.py", line 517, in close
    self.wb.close()
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 286, in close
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 500, in _store_workbook
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 1271, in _add_chart_data
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 1330, in _get_chart_range
  File "build\bdist.win32\egg\xlsxwriter\utility.py", line 108, in xl_cell_to_rowcol
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jayatsandia** [comment]
Solved the issue by adding additional chart.add_series parameter: 'categories_data' and 'values_data'.

chart.add_series({
        'name':       '=Interval!$B$1',
        'categories': '=Interval!$B$2:$B$97',
        'values':     '=Interval!$C$2:$C$97',
        # Add these properties.
        'categories_data': [], 
        'values_data':     []
    })

See: https://github.com/jmcnamara/XlsxWriter/issues/296#ref-commit-49038b2
